=== MJKruszewski/rokugan-manager-app/src/assets/data/json_schema/samurai_heritage.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "Samurai heritage",
    "description": "List of potential famous relatives",
    "type": "array",
    "items": {
        "description": "Potential famous relative",
        "type": "object",
        "properties": {
            "roll": {
                "description": "Range of die value associated with this famous relative",
                "type": "object",
                "properties": {
                    "min": {
                        "type": "integer"
                    },
                    "max": {
                        "type": "integer"
                    }
                },
                "required": [
                    "min",
                    "max"
                ],
                "defaultSnippets": [
                    {
                        "label": "New Range of die value associated with this famous relative",
                        "body": {
                            "min": "^$1",
                            "max": "^$2"
                        }
                    }
                ]
            },
            "result": {
                "description": "Description of this famous relative",
                "type": "string"
            },
            "modifiers": {
                "description": "Effect of famous relative on social attributes",
                "type": "object",
                "properties": {
                    "glory": {
                        "type": "integer"
                    },
                    "honor": {
                        "type": "integer"
                    },
                    "status": {
                        "type": "integer"
                    }
                },
                "required": [
                    "glory",
                    "honor",
                    "status"
                ],
                "defaultSnippets": [
                    {
                        "label": "New Effect of famous relative on social attributes",
                        "body": {
                            "glory": "^$1",
                            "honor": "^$2",
                            "status": "^$3"
                        }
                    }
                ]
            },
            "other_effects": {
                "description": "Other effects famous relative has",
                "type": "object",
                "properties": {
                    "type": {
                        "description": "Type of effect",
                        "type": "string"
                    },
                    "instructions": {
                        "description": "Instructions for determining effect",
                        "type": "string"
                    },
                    "outcomes": {
                        "description": "For effects determined by die rolls, outcome of effect based die value",
                        "type": "array",
                        "items": {
                            "description": "Mapping from die value to outcome",
                            "type": "object",
                            "properties": {
                                "roll": {
                                    "description": "Range of die values corresponding to the outcome",
                                    "type": "object",
                                    "properties": {
                                        "min": {
                                            "type": "integer"
                                        },
                                        "max": {
                                            "type": "integer"
                                        }
                                    },
                                    "required": [
                                        "min",
                                        "max"
                                    ],
                                    "defaultSnippets": [
                                        {
                                            "label": "New Range of die values corresponding to the outcome",
                                            "body": {
                                                "min": "^$1",
                                                "max": "^$2"
                                            }
                                        }
                                    ]
                                },
                                "outcome": {
                                    "description": "Outcome to range of die values",
                                    "type": "string"
                                }
                            },
                            "required": [
                                "outcome"
                            ],
                            "defaultSnippets": [
                                {
                                    "label": "New Mapping from die value to outcome",
                                    "body": {
                                        "roll": "^$1",
                                        "outcome": "$2"
                                    }
                                }
                            ]
                        }
                    }
                },
                "required": [
                    "type",
                    "instructions"
                ],
                "defaultSnippets": [
                    {
                        "label": "New Other effects famous relative has",
                        "body": {
                            "type": "$1",
                            "instructions": "$2",
                            "outcomes": "^[$3]"
                        }
                    }
                ]
            },
            "source": {
                "description": "Source of samurai heritage table to which this roll belongs",
                "type": "string"
            }
        },
        "required": [
            "roll",
            "result",
            "modifiers",
            "other_effects",
            "source"
        ],
        "defaultSnippets": [
            {
                "label": "New Potential famous relative",
                "body": {
                    "roll": "^$1",
                    "result": "$2",
                    "modifiers": "^$3",
                    "other_effects": "^$4",
                    "source": "$5"
                }
            }
        ]
    }
}

=== MJKruszewski/rokugan-manager-app/src/assets/data/json/samurai_heritage.json
[
    {
        "roll": {
            "min": 1,
            "max": 1
        },
        "result": "Famous Deed",
        "modifiers": {
            "glory": 3,
            "honor": 0,
            "status": 0
        },
        "other_effects": {
            "type": "starting item",
            "instructions": "Roll a ten-sided die again and add the resulting family heirloom to your starting items. You choose one quality and the GM chooses one quality from the list of item qualities, on page 240; these are applied to the item.",
            "outcomes": [
                {
                    "roll": {
                        "min": 1,
                        "max": 3
                    },
                    "outcome": "weapon"
                },
                {
                    "roll": {
                        "min": 4,
                        "max": 6
                    },
                    "outcome": "set of armor"
                },
                {
                    "roll": {
                        "min": 7,
                        "max": 8
                    },
                    "outcome": "another item"
                },
                {
                    "roll": {
                        "min": 9,
                        "max": 9
                    },
                    "outcome": "horse or other animal"
                },
                {
                    "roll": {
                        "min": 10,
                        "max": 10
                    },
                    "outcome": "boat or estate"
                }
            ]
        },
        "source": "Core"
    },
    {
        "roll": {
            "min": 2,
            "max": 2
        },
        "result": "Glorious Sacrifice",
        "modifiers": {
            "glory": 5,
            "honor": 5,
            "status": 0
        },
        "other_effects": {
            "type": "lost family heirloom",
            "instructions": "Roll a ten-sided die again to determin your lost family heirloom, which exists somewhere in the world. You choose one quality and the GM chooses one quality; these are applied to the item. You do not know where the heirloom is, but you could later reclaim it during the campaign.",
            "outcomes": [
                {
                    "roll": {
                        "min": 1,
                        "max": 3
                    },
                    "outcome": "weapon"
                },
                {
                    "roll": {
                        "min": 4,
                        "max": 6
                    },
                    "outcome": "set of armor"
                },
                {
                    "roll": {
                        "min": 7,
                        "max": 8
                    },
                    "outcome": "another item"
                },
                {
                    "roll": {
                        "min": 9,
                        "max": 9
                    },
                    "outcome": "horse or other animal"
                },
                {
                    "roll": {
                        "min": 10,
                        "max": 10
                    },
                    "outcome": "boat or estate"
                }
            ]
        },
        "source": "Core"
    },
    {
        "roll": {
            "min": 3,
            "max": 3
        },
        "result": "Wondrous Work",
        "modifiers": {
            "glory": 5,
            "honor": 0,
            "status": 0
        },
        "other_effects": {
            "type": "Artisan skills",
            "instructions": "Roll a ten-sided die again to determine an Artisan skill; gain +1 rank in that skill.",
            "outcomes": [
                {
                    "roll": {
                        "min": 1,
                        "max": 3
                    },
                    "outcome": "Aesthetics"
                },
                {
                    "roll": {
                        "min": 4,
                        "max": 6
                    },
                    "outcome": "Composition"
                },
                {
                    "roll": {
                        "min": 7,
                        "max": 8
                    },
                    "outcome": "Design"
                },
                {
                    "roll": {
                        "min": 9,
                        "max": 10
                    },
                    "outcome": "Smithing"
                }
            ]
        },
        "source": "Core"
    },
    {
        "roll": {
            "min": 4,
            "max": 4
        },
        "result": "Dynasty Builder",
        "modifiers": {
            "glory": -3,
            "honor": 0,
            "status": 0
        },
        "other_effects": {
            "type": "Social skill",
            "instructions": "Roll a ten-sided die again to determine a Social skill; gain +1 rank in that skill",
            "outcomes": [
                {
                    "roll": {
                        "min": 1,
                        "max": 3
                    },
                    "outcome": "Command"
                },
                {
                    "roll": {
                        "min": 4,
                        "max": 6
                    },
                    "outcome": "Courtesy"
                },
                {
                    "roll": {
                        "min": 7,
                        "max": 8
                    },
                    "outcome": "Games"
                },
                {
                    "roll": {
                        "min": 9,
                        "max": 10
                    },
                    "outcome": "Performance"
                }
            ]
        },
        "source": "Core"
    },
    {
        "roll": {
            "min": 5,
            "max": 5
        },
        "result": "Discovery",
        "modifiers": {
            "glory": 3,
            "honor": 0,
            "status": 0
        },
        "other_effects": {
            "type": "Scholar skill",
            "instructions": "Roll a ten-sided die again to determine a Scholar skill; gain +1 rank in that skill",
            "outcomes": [
                {
                    "roll": {
                        "min": 1,
                        "max": 3
                    },
                    "outcome": "Culture"
                },
                {
                    "roll": {
                        "min": 4,
                        "max": 5
                    },
                    "outcome": "Sentiment"
                },
                {
                    "roll": {
                        "min": 6,
                        "max": 7
                    },
                    "outcome": "Government"
                },
                {
                    "roll": {
                        "min": 8,
                        "max": 9
                    },
                    "outcome": "Medicine"
                },
                {
                    "roll": {
                        "min": 10,
                        "max": 10
                    },
                    "outcome": "Theology"
                }
            ]
        },
        "source": "Core"
    },
    {
        "roll": {
            "min": 6,
            "max": 6
        },
        "result": "Ruthless Victor",
        "modifiers": {
            "glory": 0,
            "honor": -5,
            "status": 0
        },
        "other_effects": {
            "type": "Martial skill",
            "instructions": "Roll a ten-sided again to determine a Martial skill; gain +1 rank in that skill",
            "outcomes": [
                {
                    "roll": {
                        "min": 1,
                        "max": 3
                    },
                    "outcome": "Fitness"
                },
                {
                    "roll": {
                        "min": 4,
                        "max": 5
                    },
                    "outcome": "Martial Arts [Melee]"
                },
                {
                    "roll": {
                        "min": 6,
                        "max": 7
                    },
                    "outcome": "Martial Arts [Ranged]"
                },
                {
                    "roll": {
                        "min": 8,
                        "max": 8
                    },
                    "outcome": "Martial Arts [Unarmed]"
                },
                {
                    "roll": {
                        "min": 9,
                        "max": 9
                    },
                    "outcome": "Tactics"
                },
                {
                    "roll": {
                        "min": 10,
                        "max": 10
                    },
                    "outcome": "Meditation"
                }
            ]
        },
        "source": "Core"
    },
    {
        "roll": {
            "min": 7,
            "max": 7
        },
        "result": "Elevated for Service",
        "modifiers": {
            "glory": -3,
            "honor": 3,
            "status": 0
        },
        "other_effects": {
            "type": "Trade skill",
            "instructions": "Roll a ten-sided die again to determine a Trade skill; gain +1 rank in that skill",
            "outcomes": [
                {
                    "roll": {
                        "min": 1,
                        "max": 3
                    },
                    "outcome": "Commerce"
                },
                {
                    "roll": {
                        "min": 4,
                        "max": 5
                    },
                    "outcome": "Labor"
                },
                {
                    "roll": {
